language: java
jdk: oraclejdk8

env:
  - JAVA_OPTS ="-XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:PermSize=256M -XX:MaxPermSize=512M"

after_success:
  - ./gradlew jacocoTestReport coveralls
