language: java

env:
  - JAVA_OPTS ="-XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:PermSize=256M -XX:MaxPermSize=512M"

script:
  - cd  ethereumj-core
  - mvn clean test jacoco:report coveralls:jacoco
